Only sync github

diff --git a/bin/dropbox b/bin/dropbox
--- a/bin/dropbox
+++ b/bin/dropbox
@@ -27,6 +27,11 @@ ghq_path="$(git rev-parse --show-toplevel | sed -e 's/^\/Users\/k0kubun\///g')"
 gopath_repo="$(git rev-parse --show-toplevel)"
 dropbox_repo="${DROPBOX_DIR}/${ghq_path}"
 
+if echo $ghq_path | grep -v -q "\/github.com\/"; then
+  echo "This is not hosted on GitHub. Aborting."
+  exit 1
+fi
+
 case $1 in
   '')
     echo 'Usage dropbox [push|pull]'
